### PR TITLE
Add preact boilerplate project

### PR DESCRIPTION
**Pull request by SafdarJamal**

### CODE REVIEW

**Comment by SafdarJamal** [comment]
Hey @DeMoorJasper! Can you please merge this PR.

**Comment by mischnic** [comment]
Why do you pass `--no-cache` to parcel in the start and build script?

**Comment by SafdarJamal** [comment]
> Why do you pass `--no-cache` to parcel in the start and build script?

Just to keep it simple.

**Comment by mischnic** [comment]
> Just to keep it simple.

It just *dramatically* increases startup & built time

**Comment by SafdarJamal** [comment]
> > Just to keep it simple.
> 
> It just _dramatically_ increases startup & built time

Thanks for letting me know, i will update it accordingly.

**Pull request merged**
