### PR TITLE
Electron example

### PR DESCRIPTION
**Pull request by reed-jones**
[electron-parcel-template](https://github.com/reed-jones/electron-parcel-template/blob/master/package.json) is a small example/template of a setup electron app, with hot reloading and all of parcels goodness.

### CODE REVIEW

**Comment by DeMoorJasper** [comment]
Parcel has an API for calling a build inside JS. Might be intresting to use that instead of execa in your example

**Comment by reed-jones** [comment]
That's a good idea, thanks. I'll see if i can get that working :)

**Comment by reed-jones** [comment]
I can't seem to start the HMR/development server using the API, so for the time being I guess I will leave execa in place.

**Comment by DeMoorJasper** [comment]
Closing due to inactivity

**Pull request closed without merging**
